fix(Makefile): correct bootstrap init (#112)
refactor(ci): create reusable workflow for ecs deployment
chore(d10): remove temp commets

diff --git a/environments/bootstrap/aws/terraform/templates/ecs-image-change.yml.tmpl b/environments/bootstrap/aws/terraform/templates/ecs-image-change.yml.tmpl
--- a/environments/bootstrap/aws/terraform/templates/ecs-image-change.yml.tmpl
+++ b/environments/bootstrap/aws/terraform/templates/ecs-image-change.yml.tmpl
@@ -3,7 +3,7 @@
 name: Redeploy latest image to ECS
 
 on:
-  workflow_dispatch:
+  workflow_call:
 
 jobs:
   deploy:
@@ -16,6 +16,7 @@ jobs:
       contents: read
 
     outputs:
+      deployed: $${{ steps.get-deployment.outputs.deployed }}
       lb_dns: $${{ steps.get-lb.outputs.lb_dns }}
 
     steps:
@@ -29,10 +30,20 @@ jobs:
         run: |
 %{ for env in envs ~}
           if [ "$${GITHUB_REF}" = "refs/heads/${env.branch}" ]; then
-            aws ssm get-parameter --name "/cd/${env.prefix}/config" \
-              --with-decryption --query "Parameter.Value" --output text > ecs.json
+            NAME_PARAM="/cd/${env.prefix}/config"
           fi
 %{ endfor ~}
+
+          echo "Fetching SSM parameter: $NAME_PARAM"
+
+          if ! aws ssm get-parameter --name "$NAME_PARAM" \
+              --with-decryption --query "Parameter.Value" --output text > ecs.json 2>/dev/null; then
+            echo "Parameter $NAME_PARAM not found, skipping deployment."
+            echo "deployed=false" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          echo "deployed=true" >> $GITHUB_OUTPUT
 
           CLUSTER=$(jq -r '.cluster' ecs.json)
           SERVICE=$(jq -r '.service' ecs.json)
@@ -80,7 +91,9 @@ jobs:
   smoketest:    
     runs-on: ubuntu-latest
     needs: deploy
-    if: ${included_branches} 
+    if: |
+      (needs.deploy.outputs.deployed == 'true') &&
+      (${included_branches})
 
     permissions:
       id-token: write
