fix(Makefile): correct bootstrap init refactor(ci): create reusable workflow for ecs deployment chore(d10): remove temp commets

diff --git a/.github/workflows/ecs-image-change.yml b/.github/workflows/ecs-image-change.yml
--- a/.github/workflows/ecs-image-change.yml
+++ b/.github/workflows/ecs-image-change.yml
@@ -3,7 +3,7 @@
 name: Redeploy latest image to ECS
 
 on:
-  workflow_dispatch:
+  workflow_call:
 
 jobs:
   deploy:
@@ -16,6 +16,7 @@ jobs:
       contents: read
 
     outputs:
+      deployed: ${{ steps.get-deployment.outputs.deployed }}
       lb_dns: ${{ steps.get-lb.outputs.lb_dns }}
 
     steps:
@@ -28,17 +29,25 @@ jobs:
       - name: Fetch ECS config
         run: |
           if [ "${GITHUB_REF}" = "refs/heads/dev" ]; then
-            aws ssm get-parameter --name "/cd/dev/config" \
-              --with-decryption --query "Parameter.Value" --output text > ecs.json
+            NAME_PARAM="/cd/dev/config"
           fi
           if [ "${GITHUB_REF}" = "refs/heads/master" ]; then
-            aws ssm get-parameter --name "/cd/prod/config" \
-              --with-decryption --query "Parameter.Value" --output text > ecs.json
+            NAME_PARAM="/cd/prod/config"
           fi
           if [ "${GITHUB_REF}" = "refs/heads/stage" ]; then
-            aws ssm get-parameter --name "/cd/stage/config" \
-              --with-decryption --query "Parameter.Value" --output text > ecs.json
+            NAME_PARAM="/cd/stage/config"
           fi
+
+          echo "Fetching SSM parameter: $NAME_PARAM"
+
+          if ! aws ssm get-parameter --name "$NAME_PARAM" \
+              --with-decryption --query "Parameter.Value" --output text > ecs.json 2>/dev/null; then
+            echo "Parameter $NAME_PARAM not found, skipping deployment."
+            echo "deployed=false" >> $GITHUB_OUTPUT
+            exit 0
+          fi
+
+          echo "deployed=true" >> $GITHUB_OUTPUT
 
           CLUSTER=$(jq -r '.cluster' ecs.json)
           SERVICE=$(jq -r '.service' ecs.json)
@@ -86,7 +95,9 @@ jobs:
   smoketest:    
     runs-on: ubuntu-latest
     needs: deploy
-    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stage' 
+    if: |
+      (needs.deploy.outputs.deployed == 'true') &&
+      (github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/stage')
 
     permissions:
       id-token: write
